version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Amsterdam
      time: '07:00'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Amsterdam
      time: '07:00'