name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
      - name: Run Spotless check
        run: ./gradlew robot:spotlessCheck

  linting:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check Javadoc
        run: ./gradlew checkstyleMain checkstyleTest

  build:
    runs-on: ubuntu-latest
    needs: [formatting, linting]
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true 
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and run tests on robot code
      run: ./gradlew build -x checkstyleMain -x checkstyleTest -x spotlessCheck
